apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: eu-central-1

nodeGroups:
  - name: node-group
    instanceType: m5.large
    desiredCapacity: 1
    volumeSize: 80
